spring:
  application:
    name: airline-booking-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/airline-db
    username: root
    password: password

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
