spring:
  application:
    name: airline-booking-backend

  datasource:
    url: ${LOCAL_POSTGRESQL_DB_URL}
    username: ${LOCAL_POSTGRESQL_DB_DEFAULT_USER}
    password: ${LOCAL_POSTGRESQL_DB_DEFAULT_USER_PASSWORD}

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
