spring:
  application:
    name: airline-booking-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/Work_database
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update