spring:
  application:
    name: airline-booking-backend

  datasource:
    url: ${LOCAL_POSTGRESQL_DB_URL}
    username: ${LOCAL_POSTGRESQL_DB_DEFAULT_USER}
    password: ${LOCAL_POSTGRESQL_DB_DEFAULT_USER_PASSWORD}

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    auth: plain
    starttls:
      enable: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration:
    access-token: 300000
    refresh-token: 3_600_000

otp:
  expiration: 900000